#!/bin/bash
# runs all tests, and opens a tiled gnome-terminal window
# showing each platform's logs.
set -eu
here="$(dirname "$0")"
(
	cd "$here"
	gup -u available-hosts
	logs="$(sed -e's/$/.log/' available-hosts | sort)"
	rm -f $logs
	touch $logs
	gnome-terminal --command "0install run http://gfxmonk.net/dist/0install/tail-logs.xml $logs" --working-directory="$(pwd)"
)
gup -j10 "$here/all" >/dev/null
