#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node || (echo 'Error: could not find `node` or `nodejs`' >&2; echo false))" "$0" "$@"

// vim: syntax=sjs:

var fs = require('fs');
var path = require('path');

var sjs = require('stratifiedjs');
var base = sjs.pathToFileUrl(path.dirname(fs.realpathSync(__filename))) + '/';

exports.run = function() {
	sjs.run(sjs.normalizeURL('modules/server/main.sjs', base));
};

exports.init = function(cb) {
	sjs.require(normalizeURL('hub.sjs', base), {callback: cb});
}

if (require.main === module) {
	exports.run();
}
