#!/bin/bash

PLATFORMS="linux/amd64,linux/arm64"
BUILDER="mho-builder"

docker buildx inspect $BUILDER &> /dev/null
if [ $? -ne 0 ]; then
  docker buildx create --name $BUILDER --driver docker-container
fi
docker buildx use $BUILDER
docker buildx build --platform $PLATFORMS -t onilabs/conductance:latest --push .

